version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: magicstream-mongo
    ports:
      - "27017:27017"          # access MongoDB from host
    volumes:
      - mongo_data:/data/db    # persist DB
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo_data:
